version: 2
workflows:
  version: 2
  release:
    jobs:
      - release-staging:
          context: staging
          filters:
            branches:
              only: development
      - release-production:
          context: production
          filters:
            branches:
              only: master
jobs:
  release-staging:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install lerna
          command: yarn global add lerna
      - run:
          name: bootstrap dependencies
          command: yarn bootstrap
      - run:
          name: lerna updated
          command: yarn lerna updated
      - run:
          name: lerna release
          command: yarn publish-dependencies --yes --canary
      - run:
          name: commit changelogs
          command: "git add . && git commit -m \"chore(release): pre-release\""
      - run:
          name: print git status
          command: git status
      - run:
          name: push changes
          command: git push origin development
  release-production:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install lerna
          command: yarn global add lerna
      - run:
          name: bootstrap dependencies
          command: yarn bootstrap
      - run:
          name: lerna updated
          command: yarn lerna updated
      - run:
          name: lerna release
          command: yarn publish-dependencies --yes
      - run:
          name: print git status
          command: git status
