version: 2
workflows:
  version: 2
  release-staging:
    jobs:
      - release-staging:
          context: staging
          filters:
            branches:
              only: development
  release-production:
    jobs:
      - release-production:
          context: production
          filters:
            branches:
              only: master
jobs:
  release-staging:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: yarn global add lerna lerna-changelog
      - run:
          name: bootstrap lerna
          command: yarn bootstrap
      - run:
          name: changelog
          command: yarn lerna-changelog
      - run:
          name: git status 1
          command: git status
      - run:
          name: lerna release
          command: yarn publish-dependencies --yes --canary
      - run:
          name: git status 2
          command: git status
  release-production:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: yarn global add lerna
      - run:
          name: bootstrap lerna
          command: yarn bootstrap
      - run:
          name: changelog
          command: yarn lerna-changelog
      - run:
          name: git status 1
          command: git status
      - run:
          name: lerna release
          command: yarn publish-dependencies --yes
      - run:
          name: git status 2
          command: git status
