version: 2
workflows:
  version: 2
  release-and-deploy-staging:
    jobs:
      - release-and-deploy:
          context: staging
          filters:
            branches:
              only: next
  release-and-deploy-production:
    jobs:
      - release-and-deploy:
          context: production
          filters:
            branches:
              only: master
jobs:
  release-and-deploy:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install yarn
          command: |
            curl -sL https://deb.nodesource.com/setup_10.x | bash - 
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
            apt-get update
            apt-get install -y nodejs
            apt-get install yarn
      - run:
          name: Store Service Account
          command: echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/gcloud-service-key.json
      - run:
          name: Setup gcloud client
          command: | 
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
      - setup-docker-engine
      - run:
          name: Setup docker client
          command: gcloud auth configure-docker
      - run:	
          name: install lerna	
          command: yarn global add lerna  
      - run:
          # move this to a safe place
          name: Install node deps
          command: npm install handlebars lodash dotenv
      - run:
          name: Publish and build templates
          command: |
            if [ "$ {CIRCLE_BRANCH}" == "next" ]; then
              node ./scripts/publishAndBuildTemplates.js 'lerna publish --cd-version prerelease'
            fi
            if [ "$ {CIRCLE_BRANCH}" == "master" ]; then
              node ./scripts/publishAndBuildTemplates.js 'lerna publish'
            fi
      - run:
          name: Deploy
          command: bash ./scripts/deploy.sh