version: 2
workflows:
  version: 2
  release-staging:
    jobs:
      - release-staging:
          context: staging
          filters:
            branches:
              only: development
  release-production:
    jobs:
      - release-production:
          context: production
          filters:
            branches:
              only: master
jobs:
  release-staging:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: lerna release
<<<<<<< Updated upstream
          command: yarn publish-dependencies
      - run:
          name: semantic release
          command: npm run semantic-release || true
  release-production:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: lerna release
          command: yarn publish-dependencies
      - run:
          name: semantic release
          command: npm run semantic-release || true
=======
          command: yarn publish-dependencies --yes --skip-npm
>>>>>>> Stashed changes
