---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-referral-ranks-invite-wrapper-{{shardId}}
  namespace: overmindbots
spec:
  replicas: 1
  selector:
    matchLabels:
      app-referral-ranks-invite-wrapper
      shardId: "{{shardId}}"
  template:
    metadata:
      labels:
        app-referral-ranks-invite-wrapper
        shardId: "{{shardId}}"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  app-referral-ranks-invite-wrapper
              topologyKey: kubernetes.io/hostname
      containers:
      - name: overmindbots-core
        command: ["/bin/sh","-c"]
        args: ["cd packages/app-referral-ranks-invite-wrapper; npm run start:production"]
        image: {{{imageUrl}}}
        imagePullPolicy: {{imagePullPolicy}}
        ports:
          - containerPort: 7000
        env:
        - name: NODE_ENV
          value: production
        - name: DEPLOYMENT_STAGE
          value: {{deploymentStage}}
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SHARD_ID
          value: "{{shardId}}"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: overmindbots-secrets
              key: MONGODB_URI
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: overmindbots-secrets
              key: BOT_TOKEN