---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: bot-referral-ranks
  namespace: overmindbots
spec:
  replicas: {{totalShards}}
  selector:
    matchLabels:
      app: bot-referral-ranks
  template:
    metadata:
      labels:
        app: bot-referral-ranks
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - bot-referral-ranks
              topologyKey: kubernetes.io/hostname
      containers:
      - name: overmindbots-core
        command: ["/bin/sh","-c"]
        args: ["cd packages/bot-referral-ranks; npm run production:start"]
        image: {{{imageUrl}}}
        imagePullPolicy: {{imagePullPolicy}}
        ports:
          - containerPort: 7000
        readinessProbe:
          httpGet:
            path: /readiness
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /liveness
            port: 7000
          initialDelaySeconds: 5
          periodSeconds: 3
        env:
        - name: NODE_ENV
          value: production
        - name: DEPLOYMENT_STAGE
          value: {{deploymentStage}}
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: overmindbots-secrets
              key: MONGODB_URI
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: overmindbots-secrets
              key: BOT_TOKEN