---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: service-bot-manager
  namespace: overmindbots
  labels:
    app: service-bot-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: service-bot-manager
  template:
    metadata:
      labels:
        app: service-bot-manager
        type: app
    spec:
      containers:
      - name: overmindbots-core
        command: ["/bin/sh","-c"]
        args: ["cd packages/service-bot-manager; npm run start:production"]
        image: {{{imageUrl}}}
        imagePullPolicy: {{imagePullPolicy}}
        ports:
        - containerPort: 4000
        # - containerPort: 7000
        # livenessProbe:
        #   httpGet:
        #     path: /liveness
        #     port: 7000
        #   initialDelaySeconds: 5
        #   periodSeconds: 3
        # readinessProbe:
        #   httpGet:
        #     path: /readiness
        #     port: 7000
        #   initialDelaySeconds: 5
        #   periodSeconds: 3
        env:
          - name: POD_STATUS_SERVER_PORT
            value: "7000"
          - name: NODE_ENV
            value: production
          - name: DEPLOYMENT_STAGE
            value: {{deploymentStage}}
          - name: BOT_REFERRAL_RANKS_TOTAL_SHARDS
            value: "{{botReferralRanksTotalShards}}"
          - name: POD_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: overmindbots-secrets
                key: MONGODB_URI
---
apiVersion: v1
kind: Service  
metadata:  
  name: service-bot-manager
  namespace: overmindbots
  labels:
    app: service-bot-manager
spec:  
  selector:
    app: service-bot-manager
  ports:
  - name: ws-server-port
    port: 4000
    nodePort: 30005
  type: NodePort